move WPPRINT.DEF unresolv
move WPSPOOL.DEF unresolv
move WPJOB.DEF unresolv
move WPPORT.DEF unresolv
move WPPDRV.DEF unresolv
move WPQDR.DEF unresolv
move WPPDR.DEF unresolv
move WPTEMPS.DEF unresolv
move WPFILTER.DEF unresolv
move WPMINWIN.DEF unresolv
move WPCNRVW.DEF unresolv
move WPFINDER.DEF unresolv
move WPMWV.DEF unresolv
move WPPGMGRP.DEF unresolv
move WPFNDFDR.DEF unresolv
move WPDISKCV.DEF unresolv
move WPFLDRCV.DEF unresolv
move WPRPRINT.DEF unresolv
move WPCLSMGR.DEF unresolv
move WPCMDF.DEF unresolv
